### ISSUE TITLE
RuntimeError: checkpoint url or path is invalid

### ISSUE THREAD

**Issue by zelenooki87** [cswry/SeeSR#2]
Hi. Thank you for your wonderful project.
However I dhave not success to run it:
```python test_seesr.py --pretrained_model_path preset/models/stable-diffusion-2-base --prompt None --seesr_model_path preset/models/seesr --ram_ft_path preset/models/DAPE.pth --image_path preset/datasets/test_datasets --output_dir preset/datasets/output --start_point lr --num_inference_steps 50 --guidance_scale 5.5 --process_size 512
C:\Users\mikazmaj\SeeSR\pipelines\pipeline_seesr.py:42: FutureWarning: Importing `DiffusionPipeline` or `ImagePipelineOutput` from diffusers.pipeline_utils is deprecated. Please import from diffusers.pipelines.pipeline_utils instead.
  from diffusers.pipeline_utils import DiffusionPipeline
/encoder/layer/0/crossattention/self/query is tied
/encoder/layer/0/crossattention/self/key is tied
/encoder/layer/0/crossattention/self/value is tied
/encoder/layer/0/crossattention/output/dense is tied
/encoder/layer/0/crossattention/output/LayerNorm is tied
/encoder/layer/0/intermediate/dense is tied
/encoder/layer/0/output/dense is tied
/encoder/layer/0/output/LayerNorm is tied
/encoder/layer/1/crossattention/self/query is tied
/encoder/layer/1/crossattention/self/key is tied
/encoder/layer/1/crossattention/self/value is tied
/encoder/layer/1/crossattention/output/dense is tied
/encoder/layer/1/crossattention/output/LayerNorm is tied
/encoder/layer/1/intermediate/dense is tied
/encoder/layer/1/output/dense is tied
/encoder/layer/1/output/LayerNorm is tied
Loading default thretholds from .txt....
--------------
preset/models/ram_swin_large_14m.pth
--------------
Traceback (most recent call last):
  File "C:\Users\mikazmaj\SeeSR\test_seesr.py", line 265, in <module>
    main(args)
  File "C:\Users\mikazmaj\SeeSR\test_seesr.py", line 168, in main
    model = load_tag_model(args, accelerator.device)
  File "C:\Users\mikazmaj\SeeSR\test_seesr.py", line 125, in load_tag_model
    model = ram(pretrained='preset/models/ram_swin_large_14m.pth',
  File "C:\Users\mikazmaj\SeeSR\ram\models\ram_lora.py", line 325, in ram
    model, msg = load_checkpoint_swinlarge(model, pretrained, kwargs)
  File "C:\Users\mikazmaj\SeeSR\ram\models\utils.py", line 296, in load_checkpoint_swinlarge
    raise RuntimeError('checkpoint url or path is invalid')
RuntimeError: checkpoint url or path is invalid
```

**Comment by zelenooki87** [comment]
Sorry for quistion.
I was able to use project when downloaded model to:
https://huggingface.co/spaces/xinyu1205/recognize-anything/blob/main/ram_swin_large_14m.pth

BEST IMAGE SUPER RESOLUTION I have ever seen! Thank you very much! Wish you all the best Sir!

**Comment by cswry** [comment]
Thanks for youre attention!
