### ISSUE TITLE
Is it Not compatible with Win or Mac?

### ISSUE THREAD

**Issue by R031726** [cswry/SeeSR#26]
The model imports the module ‘triton’, but this module only has a Linux version and is not compatible with Windows or Mac. Has anyone succeeded in running it on Win10? What should I do?

Error information: 
```
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\envs\SeeSR\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "D:\ProgramData\anaconda3\envs\SeeSR\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
```

**Comment by deepfree2023** [comment]
https://github.com/PrashantSaikia/Triton-for-Windows
