### ISSUE TITLE
The file missing

### ISSUE THREAD

**Issue by itgrape** [cswry/SeeSR#32]
Hello
I followed the Quick Inference however when I got to run python test_seesr.py I get the following:
```
Traceback (most recent call last):
  File "test_seesr.py", line 268, in <module>
    main(args)
  File "test_seesr.py", line 167, in main
    pipeline = load_seesr_pipeline(args, accelerator, enable_xformers_memory_efficient_attention)
  File "test_seesr.py", line 83, in load_seesr_pipeline
    unet = UNet2DConditionModel.from_pretrained(args.seesr_model_path, subfolder="unet")
  File "D:\Compiler\anaconda3\envs\seesrf\lib\site-packages\diffusers\models\modeling_utils.py", line 618, in from_pretrained
    model_file = _get_model_file(
  File "D:\Compiler\anaconda3\envs\seesrf\lib\site-packages\diffusers\utils\hub_utils.py", line 284, in _get_model_file
    raise EnvironmentError(
OSError: Error no file named diffusion_pytorch_model.bin found in directory preset/models/seesr.
```
I checked the folder and found that the file was not in Google Drive either.

**Comment by Zhangjialu126** [comment]
How did you figure it out? I meet the same question.😢

**Comment by itgrape** [comment]
I ran this project a while ago, but it's been so long that I've forgotten
how I solved it. You can try this issue[
https://github.com/cswry/SeeSR/issues/15] or download the model from
Hugging Face.

Jialu Zhang ***@***.***> 于2024年11月27日周三 20:25写道：
