### ISSUE TITLE
The checkpoints can not load

### ISSUE THREAD

**Issue by Explore008** [cswry/SeeSR#5]
Hello! Your work is excellent! In the process of replicating the experiment, I loaded the pre-training file on google drive, but the loading failed, I want to know how to solve it, thank you!
Traceback (most recent call last):
  File "test_seesr.py", line 265, in <module>
    main(args)
  File "test_seesr.py", line 167, in main
    pipeline = load_seesr_pipeline(args, accelerator, enable_xformers_memory_efficient_attention)
  File "test_seesr.py", line 83, in load_seesr_pipeline
    unet = UNet2DConditionModel.from_pretrained(args.seesr_model_path, subfolder="unet")
  File "/root/miniconda3/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 646, in from_pretrained
    raise ValueError(
ValueError: Cannot load <class 'models.unet_2d_condition.UNet2DConditionModel'> from preset/models/seesr because the following keys are missing:
![c9c8268b3ac5bc3ccdcd6344d6b011b](https://github.com/cswry/SeeSR/assets/111834651/fa2aac1e-8978-4982-ade2-2ce6ea94aea6)
![e2581c091d9f8b5a7ef3c6f73acbc65](https://github.com/cswry/SeeSR/assets/111834651/a26ade9c-b030-4213-8898-7f3707779af3)
The seesr-model_path is ''Seesr-main/preset/models/seesr''
I don't know if it's because of the safetensor file format.

**Comment by cswry** [comment]
Please verify if the placement of the pre-trained models matches the path mentioned in the inference command. 

You need to consider the location of models such as SD2.1, SeeSR, RAM, and DAPE.

**Comment by rainsoulsrx** [comment]
> Hello! Your work is excellent! In the process of replicating the experiment, I loaded the pre-training file on google drive, but the loading failed, I want to know how to solve it, thank you! Traceback (most recent call last): File "test_seesr.py", line 265, in main(args) File "test_seesr.py", line 167, in main pipeline = load_seesr_pipeline(args, accelerator, enable_xformers_memory_efficient_attention) File "test_seesr.py", line 83, in load_seesr_pipeline unet = UNet2DConditionModel.from_pretrained(args.seesr_model_path, subfolder="unet") File "/root/miniconda3/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 646, in from_pretrained raise ValueError( ValueError: Cannot load <class 'models.unet_2d_condition.UNet2DConditionModel'> from preset/models/seesr because the following keys are missing: ![c9c8268b3ac5bc3ccdcd6344d6b011b](https://private-user-images.githubusercontent.com/111834651/292961171-fa2aac1e-8978-4982-ade2-2ce6ea94aea6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTE0NzYsIm5iZiI6MTcyMDUxMTE3NiwicGF0aCI6Ii8xMTE4MzQ2NTEvMjkyOTYxMTcxLWZhMmFhYzFlLTg5NzgtNDk4Mi1hZGUyLTJjZTZlYTk0YWVhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQwNzQ2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjU1MWFjOTlmMmZiODJhZTIwMzU1MDE2NTgxMTczOWU4YWQwMTM1OGJmMmUwZjkzYWQ1MWFlYTc5YjkyZWNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8-KD2U1aAbhUol9hTlJdgqg0KTWsdmT2tTxCudgBemI) ![e2581c091d9f8b5a7ef3c6f73acbc65](https://private-user-images.githubusercontent.com/111834651/292961178-a26ade9c-b030-4213-8898-7f3707779af3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTE0NzYsIm5iZiI6MTcyMDUxMTE3NiwicGF0aCI6Ii8xMTE4MzQ2NTEvMjkyOTYxMTc4LWEyNmFkZTljLWIwMzAtNDIxMy04ODk4LTdmMzcwNzc3OWFmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQwNzQ2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmM3ZTM0YWY2YzUxM2VmODM4MzA3OTU0MmZjNjcwM2EwMjRmNTAzZmIyNDZlNzczOGI1NjM0YzQxNzQwMDFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w97CxVYf7-9toi0PrJShvI3gtKZ0DIbhOrFUKIMqO-U) The seesr-model_path is ''Seesr-main/preset/models/seesr'' I don't know if it's because of the safetensor file format.The command line parameters are the same as those in readme.

Have you solved this?
