### ISSUE TITLE
About the pretrained weights loading problem in training

### ISSUE THREAD

**Issue by llstela** [cswry/SeeSR#67]
While loading **UNet2DConditionModel** from pretrained SD-2, **ValueError** appears, as parameter weights related to image_attentions are missed.

> Traceback (most recent call last):
>   File "train_seesr.py", line 680, in <module>
>     unet = UNet2DConditionModel.from_pretrained(
>   File "/opt/conda/envs/seesr/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 646, in from_pretrained
>     raise ValueError(
> ValueError: Cannot load <class 'models.unet_2d_condition.UNet2DConditionModel'> from preset/models/stable-diffusion-2-base 
> because the following keys are missing:
> down_blocks.1.**image_attentions**.0.transformer_blocks.0.ff.net.2.bias, up_blocks.3.**image_attentions**.0.norm.weight, down_blocks.1.**image_attentions**.1.transformer_blocks.0.attn1.to_out.0.weight, ...

**Comment by Zebraside** [comment]
I have the same problem. It seems that the problem arises when `use_image_cross_attention=True` in `UNet2DConditionModel.from_pretrained`.  It is not used in some inference scripts. 

Can someone clarify is it a mandatory setting for training?

**Comment by Renzhihan** [comment]
May I ask if you get a mismatch between the output SR image and the input LR image at the beginning of the training?
Meanwhile, I think the parameter of **image_attentions** is included in the model trained by the author, not the sd2. And you can specify the **unet_model_name_or_path** and **controlnet_model_name_or_path** in the train_seesr.py.
@llstela @Zebraside

**Comment by Zebraside** [comment]
The error occurs when only `--pretrained_model_name_or_path` is set. (`# resume from pretrained SD` branch).
I'm using `stable-diffusion-2-base` from HuggingFace as base model.

**Comment by 1343464520** [comment]
i came across the same error. what's the finnal solution? @Zebraside @Renzhihan @llstela @cswry

**Comment by 1343464520** [comment]
> i came across the same error. what's the finnal solution? [@Zebraside](https://github.com/Zebraside) [@Renzhihan](https://github.com/Renzhihan) [@llstela](https://github.com/llstela) [@cswry](https://github.com/cswry)

set use_image_cross_attention=False，the error was solved
